{{- $config := .Values.config -}}
{{- $global := .Values.global -}}
{{- $name := $config.name -}}

{{- if .Values.enabled }}

apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ $config.appLabel }}
  name: {{ $name }}
spec:
  ports:
    - name: {{ $name }}-8080-8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: {{ $config.appLabel }}
    name: {{ $name }}
  sessionAffinity: None
  type: ClusterIP
---
{{- if (eq $global.localCluster true) }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ $config.appLabel }}
  name: {{ $name }}-local
spec:
  ports:
    - name: {{ $name }}-{{ $config.route.servicePort }}-8080-tcp-local
      port: {{ $config.route.servicePort }}
      protocol: TCP
      targetPort: 8080
  selector:
    app: {{ $config.appLabel }}
    name: {{ $name }}
  sessionAffinity: None
  type: LoadBalancer
---
{{- end }}
{{- end }}
