global:
  target: k8s # k8s or okd
  # To use a custom registry without affecting global values, set the value "imageRegistry"
  imageRegistry: registry.hub.docker.com/library
  # To use a custom registry secrets, set the YAML value "imagePullSecrets"
  #imagePullSecrets:
  #  <YAML secrets config here>
config:
  # To use a custom registry without affecting global values, set the value "imageRegistry"
  #imageRegistry: registry.hub.docker.com/library

  # To use a custom registry secrets without affecting global values, set the YAML value "imagePullSecrets"
  #imagePullSecrets:
  #  <YAML secrets config here>

  imageName: "mongo"
  imageVersion: "4.2.1"
  imagePullPolicy: IfNotPresent

  appLabel: mongo
  name: mongo

  replicas: 1
  resources:
    limits:
      memory: 1.5Gi
    requests:
      cpu: 5m
      memory: 240Mi

# Enable/disable mongo
enabled: true

databases:
  - dbos
  - scenario
  - execution
  - permission


