{{- range .Values.pullers }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ .name }}
data:
  .dockerconfigjson: {{ .dockerconfigjson }}
{{- end }}
