version: '2.2'
services:
  gateway-service:
    image: ${APP_DOCKER_REGISTRY}/capacity-planning/gateway-service:${PROJECT_VERSION_DOCKER_TAG}
    container_name: capacity-planning-gateway-service
    networks:
      - capacity-planning
    ports:
      - 8080:8080
#      - 5005:5005  # Expose locally the remote debug port
    environment:
#      Enable java remote debugging  (uncomment the port too)
#      - JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:5005"
      - SERVICES_DATA_HOST=data-service
      - SERVICES_DATA_PORT=8080
      - SERVICES_SCENARIO_HOST=scenario-service
      - SERVICES_SCENARIO_PORT=8080
      - SERVICES_EXECUTION_HOST=execution-service
      - SERVICES_EXECUTION_PORT=8080
      - SERVICES_BACKEND_HOST=backend-service
      - SERVICES_BACKEND_PORT=8080
      - SERVICES_DOCUMENTATION_HOST=documentation-service
      - SERVICES_DOCUMENTATION_PORT=3000
      - SERVICES_WEB_HOST=web
      - SERVICES_WEB_PORT=8080
  scenario-service:
    image: ${APP_DOCKER_REGISTRY}/capacity-planning/scenario-service:${PROJECT_VERSION_DOCKER_TAG}
    container_name: capacity-planning-scenario-service
    networks:
      - capacity-planning
#    ports:
#      - 5005:5005  # Expose locally the remote debug port
    environment:
#      Enable java remote debugging  (uncomment the port too)
#      - JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:5005"
      - KEYCLOAK_AUTH_SERVER_URL=http://keycloak:8080/auth
      - SPRING_RABBITMQ_ADDRESSES=rabbitmq
      - SPRING_DATA_MONGODB_HOST=mongo
      - SERVICES_PERMISSION_MONGODB_HOST=mongo
      - SERVICES_SESSIONTRACKING_MONGODB_HOST=mongo
      - SERVICES_DATA_HOST=data-service
      - SERVICES_DATA_PORT=8080
      - SERVICES_SCENARIO_HOST=scenario-service
      - SERVICES_SCENARIO_PORT=8080
      - SERVICES_EXECUTION_HOST=execution-service
      - SERVICES_EXECUTION_PORT=8080
      - SERVICES_BACKEND_HOST=backend-service
      - SERVICES_BACKEND_PORT=8080
      - SERVICES_DOCUMENTATION_HOST=documentation-service
      - SERVICES_DOCUMENTATION_PORT=3000
      - SERVICES_WEB_HOST=web
      - SERVICES_WEB_PORT=8080
      - WEBSOCKET_ALLOWEDORIGIN # Not specifying a value allow to transmit .env variable to container
#      - LOGGING_LEVEL_COM_DECISIONBRAIN_GENE_PERMISSION_SERVICE=DEBUG
  data-service:
    image: ${APP_DOCKER_REGISTRY}/capacity-planning/data-service:${PROJECT_VERSION_DOCKER_TAG}
    container_name: capacity-planning-data-service
    networks:
      - capacity-planning
#    ports:
#      - 5005:5005  # Expose locally the remote debug port
    environment:
#      Enable java remote debugging  (uncomment the port too)
#      - JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:5005"
      - SPRING_PROFILES_ACTIVE=keycloak
      - KEYCLOAK_AUTH_SERVER_URL=http://keycloak:8080/auth
      - SPRING_RABBITMQ_ADDRESSES=rabbitmq
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/data_server?reWriteBatchedInserts=true
      - SPRING_DATA_MONGODB_HOST=mongo
      - SERVICES_PERMISSION_MONGODB_HOST=mongo
      - SERVICES_DATA_HOST=data-service
      - SERVICES_DATA_PORT=8080
      - SERVICES_SCENARIO_HOST=scenario-service
      - SERVICES_SCENARIO_PORT=8080
      - SERVICES_EXECUTION_HOST=execution-service
      - SERVICES_EXECUTION_PORT=8080
      - SERVICES_BACKEND_HOST=backend-service
      - SERVICES_BACKEND_PORT=8080
      - SERVICES_DOCUMENTATION_HOST=documentation-service
      - SERVICES_DOCUMENTATION_PORT=3000
      - SERVICES_WEB_HOST=web
      - SERVICES_WEB_PORT=8080
      - WEBSOCKET_ALLOWEDORIGIN # Not specifying a value allow to transmit .env variable to container
  execution-service:
    image: ${APP_DOCKER_REGISTRY}/capacity-planning/execution-service:${PROJECT_VERSION_DOCKER_TAG}
    container_name: capacity-planning-execution-service
    networks:
      - capacity-planning
#    ports:
#      - 5005:5005  # Expose locally the remote debug port
    environment:
#      Enable java remote debugging  (uncomment the port too)
#      - JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:5005"
      - KEYCLOAK_AUTH_SERVER_URL=http://keycloak:8080/auth
      - SPRING_RABBITMQ_ADDRESSES=rabbitmq
      - SPRING_DATA_MONGODB_HOST=mongo
      - SERVICES_PERMISSION_MONGODB_HOST=mongo
      - OPTIMSERVER_URL=http://dbos-master:8080
      - SERVICES_DATA_HOST=data-service
      - SERVICES_DATA_PORT=8080
      - SERVICES_SCENARIO_HOST=scenario-service
      - SERVICES_SCENARIO_PORT=8080
      - SERVICES_EXECUTION_HOST=execution-service
      - SERVICES_EXECUTION_PORT=8080
      - SERVICES_BACKEND_HOST=backend-service
      - SERVICES_BACKEND_PORT=8080
      - SERVICES_DOCUMENTATION_HOST=documentation-service
      - SERVICES_DOCUMENTATION_PORT=3000
      - SERVICES_WEB_HOST=web
      - SERVICES_WEB_PORT=8080
      - WEBSOCKET_ALLOWEDORIGIN # Not specifying a value allow to transmit .env variable to container
#      - LOGGING_LEVEL_COM_DECISIONBRAIN_GENE_PERMISSION_SERVICE=DEBUG
  backend-service:
    image: ${APP_DOCKER_REGISTRY}/capacity-planning/backend-service:${PROJECT_VERSION_DOCKER_TAG}
    container_name: capacity-planning-backend-service
    networks:
      - capacity-planning
#    ports:
#      - 5005:5005  # Expose locally the remote debug port
    environment:
#      Enable java remote debugging  (uncomment the port too)
#      - JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:5005"
      - KEYCLOAK_AUTH_SERVER_URL=http://keycloak:8080/auth
      - SPRING_RABBITMQ_ADDRESSES=rabbitmq
      - SERVICES_PERMISSION_MONGODB_HOST=mongo
      - SERVICES_DATA_HOST=data-service
      - SERVICES_DATA_PORT=8080
      - SERVICES_SCENARIO_HOST=scenario-service
      - SERVICES_SCENARIO_PORT=8080
      - SERVICES_EXECUTION_HOST=execution-service
      - SERVICES_EXECUTION_PORT=8080
      - SERVICES_BACKEND_HOST=backend-service
      - SERVICES_BACKEND_PORT=8080
      - SERVICES_DOCUMENTATION_HOST=documentation-service
      - SERVICES_DOCUMENTATION_PORT=3000
      - SERVICES_WEB_HOST=web
      - SERVICES_WEB_PORT=8080
  web:
    image: ${APP_DOCKER_REGISTRY}/capacity-planning/web:${PROJECT_VERSION_DOCKER_TAG}
    container_name: capacity-planning-web
    networks:
      - capacity-planning
    environment:
      - KEYCLOAK_AUTH_SERVER_URL=http://localhost:9090/auth
networks:
  capacity-planning:
    external: true
