{{- $config := .Values.config -}}
{{- $global := .Values.global -}}
{{- $name := $config.name -}}

{{- if .Values.enabled }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ $name }}-init-scripts"
data:
  10-create_user.sh: |
    #!/bin/bash
    set -e
    echo "Creating role $POSTGRESQL_keycloak_username }} for database $POSTGRESQL_keycloak_database }}"
    psql --set password="'$POSTGRESQL_keycloak_password'" --set username="$POSTGRESQL_keycloak_username" <<-EOSQL
    CREATE USER :username WITH CREATEDB PASSWORD :password;
    EOSQL
    echo "Creating role $POSTGRESQL_dataServer_username }} for database $POSTGRESQL_dataServer_database }}"
    psql --set password="'$POSTGRESQL_dataServer_password'" --set username="$POSTGRESQL_dataServer_username" <<-EOSQL
    CREATE USER :username WITH CREATEDB PASSWORD :password;
    EOSQL
  20-create_db.sh: |
    #!/bin/bash
    set -e
    echo "Creating database keycloak with role: $POSTGRESQL_keycloak_username }}"
    psql --set database="$POSTGRESQL_keycloak_database" --set username="'$POSTGRESQL_keycloak_username'" <<EOSQL
    CREATE DATABASE :database OWNER :username;
    EOSQL
    echo "Creating database dataServer with role: $POSTGRESQL_dataServer_username }}"
    psql --set database="$POSTGRESQL_dataServer_database" --set username="'$POSTGRESQL_dataServer_username'" <<EOSQL
    CREATE DATABASE :database OWNER :username;
    EOSQL
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ $config.appLabel }}
  name: {{ $name }}
spec:
  ports:
    - name: 5432-tcp
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: {{ $config.appLabel }}
    name: {{ $name }}
  sessionAffinity: None
  type: ClusterIP
---
{{- end }}
