{{- $config := .Values.keycloak.config -}}
{{- $name := $config.name -}}

{{- if .Values.keycloak.enabled }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $config.name }}-provisioning-data
data:
  realm.json: |
{{- if .Values.keycloak.realm }}
{{ tpl .Values.keycloak.realm . | indent 4 }}
{{- else }}
{{ tpl (.Files.Get .Values.keycloak.defaultRealmFileName) . | indent 4 }}
{{- end }}
---
{{- end }}
