{{- if eq .Values.global.target "k8s" }}
{{- $dockerSecrets := .Values.global.docker.imagePullSecrets -}}
  {{- range .Values.workers }}
  {{- $appLabel := "workers" -}}
  {{- $serviceName := printf "%s-worker" .name -}}
  {{- $defaultDockerImage := printf "%s/%s:%s" $.Values.global.docker.registry $serviceName $.Values.global.appVersion -}}
  {{- $dockerImage := .dockerImage | default $defaultDockerImage -}}
  {{- $limits := .limits -}}
  {{- $environmentVariables := concat $.Values.global.environmentVariables $.Values.global.workers.environmentVariables .environmentVariables -}}
  {{- $monitor := .monitor}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ $appLabel }}
  name: {{ $serviceName }}
spec:
  selector:
    matchLabels:
      app: {{ $appLabel }}
      deploymentconfig: {{ $serviceName }}
  template:
    metadata:
      labels:
        app: {{ $appLabel }}
        name: {{ $serviceName }}
        deploymentconfig: {{ $serviceName }}
    spec:
      containers:
      - name: {{ $serviceName }}
        image: {{ $dockerImage | quote }}
        imagePullPolicy: {{ $.Values.global.docker.imagePullPolicy }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
        {{- if $environmentVariables }}
{{ tpl (toYaml $environmentVariables) $ | indent 8 }}
        {{- end }}
        resources:
          limits:
            memory: {{ $limits.memLimit }}
          requests:
            cpu: {{ $limits.cpuRequest }}
            memory: {{ $limits.memRequest }}
        {{- if $monitor }}
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 10
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 300
          periodSeconds: 60
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        {{- end }}
      {{- if $dockerSecrets }}
      imagePullSecrets:
        {{- range $dockerSecrets }}
        - name: {{ .name }}
        {{- end }}
      {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  {{- end }}
{{- end }}
