{{- $appLabel := .Values.global.appLabel -}}
{{- $serviceName := .Values.web.serviceName -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ $appLabel }}
  name: {{ $serviceName }}
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{ $appLabel }}
    deploymentconfig: {{ $serviceName }}
  sessionAffinity: None
  type: ClusterIP
