{{- $config := .Values.master.config -}}
{{- $global := .Values.global -}}
{{- $name := $config.name -}}
{{- $isKubernetes := (eq $global.target "k8s") -}}

{{- if $isKubernetes }}

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ $config.appLabel }}
  name: {{ $name }}
spec:
  replicas: {{ $config.replicas }}
  selector:
    matchLabels:
      app: {{ $config.appLabel }}
      name: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $config.appLabel }}
        name: {{ $name }}
    spec:
      containers:
        - image: "{{ $config.imageRegistry | default $global.imageRegistry }}/{{ $config.imageName }}:{{ tpl $config.imageVersion . }}"
          imagePullPolicy: {{ tpl $config.imagePullPolicy . }}
          name: {{ $name }}
          {{- if .Values.master.env }}
          env:
{{ tpl (toYaml .Values.master.env) . | indent 12 }}
          {{- end }}
          {{- if $config.resources }}
          resources:
{{ tpl (toYaml $config.resources) . | indent 12 }}
          {{- end }}
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 10
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 300
            periodSeconds: 60
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      {{- if $global.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml $global.imagePullSecrets | indent 12 }}
      {{- end }}
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
{{- end }}
