#master:
#    enabled: true

mongo:
#    enabled: true
#    rootUsername: #set to override defaults
#    rootPassword: #set to override defaults
    databases:
#        dbos:
#            database: #set to override defaults
#            username: #set to override defaults
#            password: #set to override defaults

        # required
        scenario:
            database: scenario-db
            username: scenario
            password: scenario

        # required
        execution:
            database: execution-db
            username: execution
            password: execution

        # required
        permission:
            database: permission-db
            username: permission
            password: permission

postgres:
#    enabled: true
#    rootPassword: #set to override defaults
    databases:
#        keycloak:
#            database: #set to override defaults
#            username: #set to override defaults
#            password: #set to override defaults

        # required
        dataServer:
            database: data_server
            username: data_server
            password: data_server

#keycloak:
#    enabled: true
#    adminPassword: #set to override defaults

pullers:
    - name: dbgene-demos-registry.decisionbrain.cloud-secret
      dockerconfigjson: ewoJImF1dGhzIjogewoJCSJkYmdlbmUtZGVtb3MtcmVnaXN0cnkuZGVjaXNpb25icmFpbi5jbG91ZCI6IHsKCQkJImF1dGgiOiAiWkdKblpXNWxMV1JsYlc5ek9tbGxVMmhoTVZCdiIKCQl9Cgl9LAoJIkh0dHBIZWFkZXJzIjogewoJCSJVc2VyLUFnZW50IjogIkRvY2tlci1DbGllbnQvMTkuMDMuNiAobGludXgpIgoJfQp9Cg==
