master:
  enabled: true
  config:
    name: dbos-master
  jwtkey: 32CharacterLengthRandomlyGeneratedString

rabbitmq:
  enabled: true
  rootUsername: guest
  rootPassword: guest
  config:
    name: rabbitmq

mongo:
  enabled: true
  rootUsername: admin
  rootPassword: admin
  config:
    name: mongo
  databases:
    dbos:
      database: optimserver-master-db
      username: optimserver
      password: optimserver
    scenario:
      database: scenario-db
      username: scenario
      password: scenario
    execution:
      database: execution-db
      username: execution
      password: execution
    permission:
      database: permission-db
      username: permission
      password: permission

postgres:
  enabled: true
  rootPassword: admin
  config:
    name: postgres
  databases:
    keycloak:
      database: keycloak
      username: keycloak
      password: keycloak
    dataServer:
      database: data_server
      username: data_server
      password: data_server

keycloak:
  enabled: true
  adminPassword: admin
  config:
    name: keycloak

pullers:
  - name: dbos-registry.decisionbrain.cloud
    dockerconfigjson: "ewoJImF1dGhzIjogewoJCSJkYmdlbmUtZGVtb3MtcmVnaXN0cnkuZGVjaXNpb25icmFpbi5jbG91ZCI6IHsKCQkJImF1dGgiOiAiWkdKblpXNWxMV1JsYlc5ek9tbGxVMmhoTVZCdiIKCQl9Cgl9LAoJIkh0dHBIZWFkZXJzIjogewoJCSJVc2VyLUFnZW50IjogIkRvY2tlci1DbGllbnQvMTkuMDMuNiAobGludXgpIgoJfQp9Cg==" # set your customer credential here
