master:
  enabled: true
  config:
    name: dbos-master
  jwtkey: 32CharacterLengthRandomlyGeneratedString

rabbitmq:
  enabled: true
  rootUsername: guest
  rootPassword: guest
  config:
    name: rabbitmq

mongo:
  enabled: true
  rootUsername: admin
  rootPassword: admin
  config:
    name: mongo
  databases:
    dbos:
      database: optimserver-master-db
      username: optimserver
      password: optimserver
    scenario:
      database: scenario-db
      username: scenario
      password: scenario
    execution:
      database: execution-db
      username: execution
      password: execution
    permission:
      database: permission-db
      username: permission
      password: permission

postgres:
  enabled: true
  rootPassword: admin
  config:
    name: postgres
  databases:
    keycloak:
      database: keycloak
      username: keycloak
      password: keycloak
    dataServer:
      database: data_server
      username: data_server
      password: data_server

keycloak:
  enabled: true
  adminPassword: admin
  config:
    name: keycloak

pullers:
  - name: default-quay-openshift
    dockerconfigjson: "eyJhdXRocyI6eyJxdWF5LXF1YXktcXVheS5yaW8tYXBzLXBvYy0xNGQ5MWZiYzQ4NDEyMmRhYzZlZWJhZTNhZjY0YmIzNS0wMDAwLmF1LXN5ZC5jb250YWluZXJzLmFwcGRvbWFpbi5jbG91ZCI6eyJhdXRoIjoiYjNCbGJuTm9hV1owWDJSdll5dGtaV1poZFd4ME9sSlZSVFJTVTFwTFVVcEhOelpIVHpCTVZ6TlFXa1pTUzFvd1dFbFJNRWRJUmxoRVdrWlhRa3RQTTFSUU9VWk1SMWhTVDFCYVNsSkxXVTFIU1VRd1dVdz0ifX19" # set your customer credential here
