apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dbos-infra
  namespace: doc
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    namespace: doc
    server: https://kubernetes.default.svc
  project: doc-project
  source:
    path: db-gene-demo-capacity-planning/dbos-infra-3.2.0-SG
    repoURL: https://github.com/Mattar555/rt-doc
    targetRevision: HEAD
