apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: doc-project
  namespace: doc
spec:
  destinations:
  - name: in-cluster
    namespace: '*'
    server: https://kubernetes.default.svc
  sourceRepos:
  - https://github.com/Mattar555/rt-doc
