{{- $config := .Values.keycloakPostinstall -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-role
  namespace: {{ $config.NAMESPACE }}
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: job-rb
  namespace: {{ $config.NAMESPACE }}
subjects:
  - kind: ServiceAccount
    name: job-sa
    namespace: {{ $config.NAMESPACE }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: job-role