{{- $config := .Values.master.config -}}
{{- $name := $config.name -}}

{{- if .Values.master.enabled }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
type: Opaque
data:
  {{- if eq .Values.master.jwtkey "auto" }}
  master-secret-jwtkey: {{ b64enc (randAlphaNum 32) }}
  {{- else }}
  master-secret-jwtkey: {{ b64enc (.Values.master.jwtkey) }}
  {{- end }}
---
{{- end }}
