{{- $config := .Values.rabbitmq.config -}}
{{- $name := $config.name -}}

{{- if .Values.rabbitmq.enabled }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
type: Opaque
data:
  rabbitmq-root-username: {{ b64enc .Values.rabbitmq.rootUsername }}
  {{- if eq .Values.rabbitmq.rootPassword "auto" }}
  rabbitmq-root-password: {{ b64enc (randAlphaNum 32) }}
  {{- else }}
  rabbitmq-root-password: {{ b64enc (.Values.rabbitmq.rootPassword) }}
  {{- end }}
---
{{- end }}
